jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Run tests per spec and generate reports
        run: |
          mkdir -p reports
          SPECS=("example.spec.ts" "playgrounddoc.spec.ts" "playgroundDynamic.spec.ts" "qaplayground.spec.ts" "screener.spec.ts")
          BROWSER="${{ github.event.inputs.browser }}"
          if [ "$BROWSER" = "edge" ]; then BROWSER="msedge"; fi

          for SPEC in "${SPECS[@]}"; do
            echo "Running $SPEC on $BROWSER ..."
            npx playwright test tests/$SPEC --project=$BROWSER --reporter=line,allure-playwright --output=allure-results-$SPEC || true
            
            # Generate individual allure report per spec
            allure generate allure-results-$SPEC --clean -o reports/$SPEC
          done

      - name: Generate combined overview report
        run: |
          allure generate allure-results-* --clean -o reports/overview

      - name: Create index.html with overview and per-spec links
        run: |
          cat <<EOF > reports/index.html
          <html>
            <head><title>Allure Test Dashboard</title></head>
            <body>
              <h1>Combined Overview</h1>
              <iframe src="overview/index.html" width="100%" height="600"></iframe>
              <h2>Individual Spec Reports</h2>
              <ul>
                <li><a href="example.spec.ts/index.html" target="_blank">example.spec.ts</a></li>
                <li><a href="playgrounddoc.spec.ts/index.html" target="_blank">playgrounddoc.spec.ts</a></li>
                <li><a href="playgroundDynamic.spec.ts/index.html" target="_blank">playgroundDynamic.spec.ts</a></li>
                <li><a href="qaplayground.spec.ts/index.html" target="_blank">qaplayground.spec.ts</a></li>
                <li><a href="screener.spec.ts/index.html" target="_blank">screener.spec.ts</a></li>
              </ul>
            </body>
          </html>
          EOF

      - name: Upload all reports artifact
        uses: actions/upload-artifact@v4
        with:
          name: Allure-All-Reports
          path: reports/
