name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Choose the browser'
        required: true
        type: choice
        default: 'chromium'
        options:
          - chromium
          - firefox
          - webkit
          - edge
      spec:
        description: 'Select the spec to run (or All)'
        required: true
        type: choice
        default: 'example.spec.ts'
        options:
          - example.spec.ts
          - playgrounddoc.spec.ts
          - playgroundDynamic.spec.ts
          - qaplayground.spec.ts
          - screener.spec.ts
          - All

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Install Allure CLI and single-file packager
        run: |
          npm install -g allure-commandline --save-dev
          npm install allure-single-html-file-js --save-dev

      - name: Run Playwright tests per spec and generate allure results
        run: |
          SPECS=("example.spec.ts" "playgrounddoc.spec.ts" "playgroundDynamic.spec.ts" "qaplayground.spec.ts" "screener.spec.ts")
          BROWSER="${{ github.event.inputs.browser }}"
          if [ "$BROWSER" = "edge" ]; then BROWSER="msedge"; fi

          if [ "${{ github.event.inputs.spec }}" = "All" ]; then
            for SPEC in "${SPECS[@]}"; do
              echo "Running $SPEC on $BROWSER ..."
              rm -rf allure-results
              npx playwright test tests/$SPEC --project=$BROWSER --reporter=line,allure-playwright
              cp -r allure-results "allure-results-$SPEC"
            done
          else
            SPEC="${{ github.event.inputs.spec }}"
            echo "Running $SPEC on $BROWSER ..."
            rm -rf allure-results
            npx playwright test tests/$SPEC --project=$BROWSER --reporter=line,allure-playwright
            cp -r allure-results "allure-results-$SPEC"
          fi

      - name: Generate individual and combined Allure reports
        run: |
          mkdir -p allure-report
          if [ "${{ github.event.inputs.spec }}" = "All" ]; then
            allure generate allure-results-* --clean -o allure-report
          else
            allure generate allure-results-${{ github.event.inputs.spec }} --clean -o allure-report
          fi

      - name: Combine into Single HTML File
        run: |
          node ./node_modules/allure-single-html-file-js/combine.js allure-report
          mv allure-report/complete.html allure-report.html
          echo "✅ Combined Allure HTML generated: allure-report.html"

      - name: Upload Combined Allure HTML Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Allure-Report-Single-File
          path: allure-report.html
