name: Playwright Tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Choose the browser'
        required: true
        type: choice
        default: 'chromium'
        options:
          - chromium
          - firefox
          - webkit
          - edge
      spec:
        description: 'Select the spec to run (or All)'
        required: true
        type: choice
        default: 'example.spec.ts'
        options:
          - example.spec.ts
          - qaplayground.spec.ts
          - All

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Run tests and generate reports
        run: |
          mkdir -p reports
          SPECS=("example.spec.ts" "qaplayground.spec.ts")
          BROWSER="${{ github.event.inputs.browser }}"
          if [ "$BROWSER" = "edge" ]; then BROWSER="msedge"; fi

          if [ "${{ github.event.inputs.spec }}" = "All" ]; then
            for SPEC in "${SPECS[@]}"; do
              echo "Running $SPEC on $BROWSER ..."
              rm -rf allure-results
              npx playwright test tests/$SPEC --project=$BROWSER --reporter=line,allure-playwright
              cp -r allure-results "allure-results-$SPEC"
              allure generate "allure-results-$SPEC" --clean -o "reports/$SPEC"
            done
            allure generate allure-results-* --clean -o reports/overview
          else
            SPEC="${{ github.event.inputs.spec }}"
            echo "Running $SPEC on $BROWSER ..."
            rm -rf allure-results
            npx playwright test tests/$SPEC --project=$BROWSER --reporter=line,allure-playwright
            cp -r allure-results "allure-results-$SPEC"
            allure generate "allure-results-$SPEC" --clean -o "reports/$SPEC"
            allure generate "allure-results-$SPEC" --clean -o reports/overview
          fi

      - name: Create index.html with overview and per-spec links
        run: |
          cat <<EOF > reports/index.html
          <html>
          <head><title>Allure Test Dashboard</title></head>
          <body>
            <h1>Combined Overview</h1>
            <iframe src="overview/index.html" width="100%" height="600"></iframe>
            <h2>Individual Spec Reports</h2>
            <ul>
              <li><a href="example.spec.ts/index.html" target="_blank">example.spec.ts</a></li>
              <li><a href="qaplayground.spec.ts/index.html" target="_blank">qaplayground.spec.ts</a></li>
            </ul>
          </body>
          </html>
          EOF

      - name: Upload all reports artifact
        uses: actions/upload-artifact@v4
        with:
          name: Allure-All-Reports
          path: reports/
